# What is Numpy?
- It is library that has collections of packages and methods


Numpy has the array data types which is used to perform the various operation

NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for large multidimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Here's a detailed overview of its importance:

### 1. **Efficient Handling of Large Datasets:**
   - **Multidimensional Arrays:** NumPy introduces the `ndarray` (N-dimensional array) object, which is far more efficient than Python’s native lists for handling large datasets. These arrays can have any number of dimensions and allow for fast access and manipulation of data.
   - **Memory Efficiency:** NumPy arrays consume less memory than equivalent data structures in pure Python, making it possible to work with large datasets that would otherwise be infeasible.

### 2. **Performance:**
   - **Vectorization:** NumPy allows for vectorized operations, which are operations performed element-wise on arrays without the need for explicit loops. This leads to significant performance improvements, as operations are implemented in compiled C code, reducing the overhead of Python loops.
   - **Broadcasting:** NumPy's broadcasting feature allows operations to be performed on arrays of different shapes, automatically expanding them to be compatible. This reduces the need for manual reshaping and enhances code performance and readability.

### 3. **Mathematical and Statistical Functions:**
   - NumPy includes a wide range of mathematical functions that can be applied to arrays. This includes basic arithmetic, trigonometric functions, linear algebra, and statistical operations.
   - **Random Number Generation:** It has robust tools for generating random numbers, which are essential for simulations and probabilistic models.

### 4. **Interoperability with Other Libraries:**
   - **Pandas:** NumPy arrays are the underlying structure for Pandas, a powerful library for data manipulation and analysis.
   - **SciPy, Scikit-learn, TensorFlow, PyTorch:** Many scientific and machine learning libraries in Python are built on top of NumPy arrays. Understanding NumPy is essential for effectively using these libraries.
   - **Integration with C/C++ and Fortran:** NumPy arrays can be passed directly to code written in C, C++, or Fortran, enabling high-performance integrations.

### 5. **Data Science and Machine Learning:**
   - **Foundation for Machine Learning:** NumPy is crucial in the data preprocessing, feature extraction, and manipulation stages, making it foundational for any machine learning pipeline.
   - **Handling Time Series Data:** With efficient operations on arrays and integration with Pandas, NumPy plays a critical role in analyzing time-series data, a common task in data science.

### 6. **Support for Complex Mathematical Operations:**
   - **Linear Algebra and Fourier Transforms:** NumPy provides built-in functions for linear algebra operations (e.g., matrix multiplication, eigenvalue decomposition) and Fourier transforms, which are essential for many scientific and engineering applications.
   - **Polynomials and Random Numbers:** It offers modules for working with polynomials and generating random numbers, which are critical for simulations.

### 7. **Ease of Use and Flexibility:**
   - **Simple Syntax:** The syntax for performing operations with NumPy is concise and similar to mathematical notation, making it accessible for users transitioning from other languages like MATLAB.
   - **Custom Data Types:** NumPy allows the definition of custom data types, making it flexible to handle specialized needs.

### 8. **Data Analytics and Visualization:**
   - **Interfacing with Visualization Libraries:** NumPy works seamlessly with visualization libraries like Matplotlib, enabling the efficient generation of graphs and plots from large datasets.

### 9. **Cross-Platform Compatibility:**
   - NumPy code is portable across different platforms and operating systems, ensuring that scientific and numerical code written in Python can run anywhere with consistent behavior.

### 10. **Open Source and Active Community:**
   - Being open-source, NumPy is constantly evolving with contributions from a large community of developers and researchers. This ensures that it remains up-to-date with the latest advancements in scientific computing.

In summary, NumPy is indispensable in the scientific computing ecosystem, offering efficient and flexible tools for handling and processing large datasets, performing complex mathematical operations, and serving as a foundation for many higher-level data science and machine learning frameworks.

### Difference Between Numpy Array and List in python

- Data types storage
- Importing module
- Numerical Operation 
- Modification capabilities
- Consumes less memory
- fast as compared to the python list
- convenient to use

In [8]:
# % time it
# %% timeit 

%timeit [j**4 for j in range(1,9)]

695 ns ± 38.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
import numpy as np

%timeit np.arange(1,9)

582 ns ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
# Creating Numpy Array

import numpy as np
x = [1,3,4]
a = np.array(x)
a.ndim

1

In [16]:
b = np.array([3,4,5,6])

In [17]:
print(type(a))

<class 'numpy.ndarray'>


In [18]:
print(type(x))

<class 'list'>


In [19]:
l = []
for i in range(1,5):
    int_l = int(input("Enter: "))
    l.append(int_l)


print(np.array(l))

[2 3 6 8]


Types of Arrays in Numpy
- 1-D Arrays
- 2-D Arrays
- 3-D Arrays
- Higher Dimensional Arrays


In [20]:
# ndim used to check the dimension

In [22]:
l = []
for i in range(1,5):
    int_l = int(input("Enter: "))
    l.append(int_l)


print(np.array(l))

[4 5 5 5]


In [24]:
# 2 D Dimension

arr2 = np.array([[1,2,3,4],[1,3,3,4]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [1 3 3 4]]
2


In [29]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [32]:
print(arr3)
print(arr3.ndim)
print(arr3.size)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
12


In [33]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[3,4,5,6]]])

In [34]:
print(arr3)

[[[1 2 3 4]
  [1 2 3 4]
  [3 4 5 6]]]


In [35]:
arr3.ndim

3

In [36]:
arr3.shape

(1, 3, 4)

In [37]:
arr1 = np.array([1,2,3,4] , ndmin=10)
print(arr1)
print(arr1.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Create NumPy Array Using Function..

- Array Filled with 0's
- Array Filled with 1's
- Create an empty array
- An Array with a range of elements
- Array diagonal element filled with 1's
- Create an array with values that are spaced linearly in a specified interval

In [41]:
# Filled with 0's 
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
Ones = np.ones(5)
Ones1 = np.ones((5,6))
print(Ones)
print()
print(Ones1)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [45]:
# Empty array
ar_em = np.empty(4)
print(ar_em)

[0. 0. 0. 0.]


In [53]:
# Range Array
ar_rn = np.arange(10)
print(ar_rn)
print()
after_reshape = ar_rn.reshape(2,5)
print(after_reshape)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
# identity matrix Diagonal element filled by 1
ar_dia = np.eye(3,3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
# identity matrix Diagonal element filled by 1
ar_dia = np.eye(4,3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [66]:
# Line Space Function 

ar_lin = np.linspace(1,10 , num = 5,dtype=float) # 5 element will created with between 1 to 10 with specific space.


In [67]:
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [68]:
# Line Space Function 

ar_lin = np.linspace(1,10 , num = 5,dtype=int) # 5 element will created with between 1 to 10 with specific space.


In [69]:
print(ar_lin)

[ 1  3  5  7 10]


# Create NumPy Arrays with Random Numbers

- rand() : the function is used to generate a random value between 0 to 1
- randn() : the function is used to generate a random value close to zero this may return positive or negative numbers as well.
- ranf() : the function for doing random sampling in numPy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0 , 1.0)
- randint() : the function used to generate a random number between an given range.

In [70]:
# random
import numpy as np
var = np.random.rand(4) # value between 0 to 1 , 4 is the size

print(var)




[0.63625354 0.04629816 0.2562914  0.17531649]


In [72]:
var1 = np.random.rand(4,5)

In [73]:
print(var1)

[[0.16879684 0.63818387 0.64403717 0.62991049 0.86002572]
 [0.32898639 0.39707117 0.43685489 0.19966162 0.94072321]
 [0.63823507 0.72337401 0.448664   0.11075313 0.67746769]
 [0.74891417 0.19748612 0.0332865  0.53410941 0.07356062]]


In [74]:
# RandN
var2 = np.random.randn(5) # randn value (-1 , 1) -> open interval does not include the end point

In [75]:
print(var2)

[-0.25903484  0.04074483 -0.52276108 -0.03941722 -0.22073312]


In [76]:
var2 = np.random.randn(5,5)

In [77]:
print(var2)

[[ 0.61273992 -0.32754689 -0.68672583 -0.51878124 -1.40023091]
 [-0.10527329 -0.98873799  2.30126768 -0.80178423 -0.40463877]
 [-1.12382636 -0.03155289  0.93090087 -0.47199998  0.60693552]
 [-0.28195866  0.78312087 -0.26796194  0.28790246 -0.01534798]
 [-1.31376897 -0.73805798 -1.2146811   0.74628631  0.28948621]]


In [78]:
# randf()
var3 = np.random.ranf(4) # [0.0 , 1.1)
print(var3)

[0.8491616  0.85022215 0.43655161 0.23988266]


In [ ]:
# Mean while we can reshape the array and can convert into the different dimension

In [89]:
# randint()
var4 = np.random.randint(1,10, size=(2,4))

In [90]:
print(var4)

[[7 1 3 5]
 [5 5 2 4]]


In [85]:
var4.shape

(5,)

### Data Types in NumPy Arrays
- bool
- int
- float
- string
- complex






In [91]:
# DTypes
var = np.array([1,2,3,4,5])

In [93]:
var.dtype

dtype('int32')

In [98]:
var = np.array(["2","4","4","45","4646","rpuesh", "r"])
var.dtype

dtype('<U6')

In [100]:
var = np.array([1,2,2,'3'])
var.dtype

dtype('<U11')

In [105]:
# Data types as function 
x = np.array([1,2,3,4] , dtype= np.int8)
print(x.dtype)


int8


In [106]:
x = np.array([1,2,3,4] , dtype='f')
print(x.dtype)


float32


In [107]:
x = np.array([1,2,3,4])
x1 = np.float32(x)
new = np.int_(x1)

print(x.dtype)
print(x1.dtype)
print(new.dtype)
print()

print(x)
print(x1)
print(new)


int32
float32
int32

[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [110]:
# Directly change the types
x3 = np.array([1,2,3,4])

x4 = x3.astype(float)
print(x3)
print(x4)
print()

print(x3.dtype)
print(x4.dtype)


[1 2 3 4]
[1. 2. 3. 4.]

int32
float64


In [111]:
# Shape and Reshaping in NumPy Arrays
var = np.array([[1,2,3,4],[2,3,4,5]])
var.shape

(2, 4)

In [112]:
var.size

8

In [113]:
var = np.array([1,2,3,4] , ndmin=4)
print(var)

[[[[1 2 3 4]]]]


In [114]:
var.ndim

4

In [115]:
var.shape

(1, 1, 1, 4)

In [121]:
# Reshape
var2 = np.array([2,3,4,5,6,6,6,9])
print(var2.ndim)

# var1 = var2.reshape(2,-1)
var1 = var2.reshape(2,4)
print(var1)
print(var1.ndim)


1
[[2 3 4 5]
 [6 6 6 9]]
2


In [126]:
#3dim
var2 = np.array([2,3,4,5,6,6,6,9])
print(var2.ndim)

# var1 = var2.reshape(2,-1,2)
var1 = var2.reshape(2,2,2)
print(var1)
print(var1.ndim)

1
[[[2 3]
  [4 5]]

 [[6 6]
  [6 9]]]
3


In [129]:
#Multiple Dimension
var2 = np.array([2,3,4,5,6,6,6,9])
print(var2.ndim)

# var1 = var2.reshape(2,-1,2)
var1 = var2.reshape(2,-1,2,1)
print(var1)
print(var1.ndim)

1
[[[[2]
   [3]]

  [[4]
   [5]]]


 [[[6]
   [6]]

  [[6]
   [9]]]]
4


# Arithmetic Operation in NumPy Arrays

- a+b : np.add(a,b)
- a-b : np.subtract(a,b)
- a*b : np.multiply(a,b)
- a/b : np.divide(a,b)
- a%b : np.mod(a,b)
- a**b : np.power(a,b)
- 1/a : np.reciprocal(a,b)

In [140]:
# Addition
import numpy as np
var = np.array([1,2,3,4])
varAdd = var+3
print(varAdd)
print()
varAdd1  = np.add(var,3)
print(varAdd1)

[4 5 6 7]

[4 5 6 7]


In [141]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = var1 + var2
print(varAdd)
print()
varAdd1  = np.add(var1,var2)
print(varAdd1)

[2 4 6 8]

[2 4 6 8]


In [144]:
# Multiplication
import numpy as np
var = np.array([1,2,3,4])
varAdd = var*3
print(varAdd)
print()
varAdd1 = np.multiply(var,3)

print()

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = var1 * var2
print(varAdd)
print()
varAdd1  = np.multiply(var1,var2)
print(varAdd1)

[ 3  6  9 12]


[ 1  4  9 16]

[ 1  4  9 16]


In [145]:
# Subtraction
# Multiplication
import numpy as np
var = np.array([1,2,3,4])
varAdd = var-3
print(varAdd)
print()
varAdd1 = np.multiply(var,3)

print()

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = var1 - var2
print(varAdd)
print()
varAdd1  = np.subtract(var1,var2)
print(varAdd1)

[-2 -1  0  1]


[0 0 0 0]

[0 0 0 0]


In [148]:
# Division
import numpy as np
var = np.array([1,2,3,4])
varAdd = var/3
print(varAdd)
print()
varAdd1 = np.divide(var,3)

print(varAdd1)

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = var1 / var2
print(varAdd)
print()
varAdd1  = np.divide(var1,var2)
print(varAdd1)

[0.33333333 0.66666667 1.         1.33333333]

[0.33333333 0.66666667 1.         1.33333333]
[1. 1. 1. 1.]

[1. 1. 1. 1.]


In [149]:
# Modulo
import numpy as np
var = np.array([1,2,3,4])
varAdd = var%3
print(varAdd)
print()
varAdd1 = np.mod(var,3)

print(varAdd1)

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = var1 % var2
print(varAdd)
print()
varAdd1  = np.multiply(var1,var2)
print(varAdd1)

[1 2 0 1]

[1 2 0 1]
[0 0 0 0]

[ 1  4  9 16]


In [150]:
# Power
import numpy as np
var = np.array([1,2,3,4])
varAdd = var**3
print(varAdd)
print()
varAdd1 = np.power(var,3)

print(varAdd1)

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = var1 ** var2
print(varAdd)
print()
varAdd1  = np.power(var1,var2)
print(varAdd1)

[ 1  8 27 64]

[ 1  8 27 64]
[  1   4  27 256]

[  1   4  27 256]


In [159]:
# reciprocal
import numpy as np
var = np.array([1,2,3,4])
varAdd = 1/var
print(varAdd)
print()
varAdd1 = np.reciprocal(var)

print(varAdd1)

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varAdd = 1 / var1
print(varAdd)
print()
varAdd1  = np.reciprocal(var1)
print(varAdd1)

[1.         0.5        0.33333333 0.25      ]

[1 0 0 0]
[1.         0.5        0.33333333 0.25      ]

[1 0 0 0]


In [161]:
# similarly can apply the same on 2d and 3d or multiple arr

Other Arithmetic Function
 - np.min(x)
 - np.max(x)
 - np.argmin(x) - position of min and max argmax
 - np.sqrt(x)
 - np.sin(x)
 - np.cos(x)
 - np.cumsum(x)

In [172]:
# 1D
var = np.array([5,12,15,34,5,5,4])
print("min value : " ,np.min(var) , "position of min value" , np.argmin(var))
print("min value : " ,np.max(var) , "Position of max value" , np.argmax(var))

min value :  4 position of min value 6
min value :  34 Position of max value 3


In [174]:
# 2D array..
var = np.array([[1,3,6,7],[6,7,2,5]])
print("min value : " , np.min(var , axis=0) ,"and " , np.min(var ,axis=1) , np.argmax(var , axis=1))
print("max value : " , np.max(var , axis=0) ,"and " , np.max(var ,axis=1) , np.argmin(var,axis=0))

min value :  [1 3 2 5] and  [1 2] [3 1]
max value :  [6 7 6 7] and  [7 7] [0 0 1 1]


In [186]:
# com sum
print(np.cumsum(var , axis=0) )
print()
print(np.cumsum(var , axis=1) )
print()

arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print()

arr = np.array([1,2,3,4,5])
print(np.cumprod(arr))

print()

arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))

print()
arr = np.array([1,2,3,4,5])
print(np.sin(arr))

print()
arr = np.array([1,2,3,4,5])
print(np.cos(arr))

[[ 1  3  6  7]
 [ 7 10  8 12]]

[[ 1  4 10 17]
 [ 6 13 15 20]]

[ 1  3  6 10 15]

[  1   2   6  24 120]

[1.         1.41421356 1.73205081 2.         2.23606798]

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [ ]:
# BroadCasting NumPy Arrays
# 1 Dimension should be same then only perform BroadCasting
# or should one dimension same 1X3 and 3X1 will perform 


In [190]:
arr1 = np.array([[1,3,4]])
arr2 = np.array([[1],
                 [2],
                 [4]])

print(arr1.shape)
print()
print(arr2.shape)
print()
print(arr1 + arr2)

(1, 3)

(3, 1)

[[2 4 5]
 [3 5 6]
 [5 7 8]]


In [201]:
arr1 = np.array([[1,3,4],[3,4,6],[2,3,5]])
arr2 = np.array([[1],
                 [3],[4]]
                 )

print(arr1.shape)
print()
print(arr2.shape)
print()
print(arr1 + arr2)

(3, 3)

(3, 1)

[[2 4 5]
 [6 7 9]
 [6 7 9]]


In [240]:
# Indexing NumPy Arrays and Slicing
import numpy as np

var = np.array([9,8,7,6,10])
#               0,1,2,3
#             -4,-3,-2,-1

print(var[1])
print(var[-3])

print()
# print(var[start: stop: step])
print(var[::-1])

# for i in var:
#     print(i)



8
7

[10  6  7  8  9]


In [245]:
var1 = np.array([[9,8,7],
                 [4,5,6]])

print(var1)
print(var1.ndim)

print()

# print(var1[0,[0,2]])
print(var1[0,0:2])
print(var1[0,2])
print(var1[0,-1])
print(var1[-1,-1])

print("Slicing")
print(var1[0::1 , 0::1])
# print(var1[start:end:step , start:end:step])


[[9 8 7]
 [4 5 6]]
2

[9 8]
7
7
6
Slicing
[[9 8 7]
 [4 5 6]]


In [246]:
var2 = np.array([[[1,2],
                  [1,2]],

                 [[3,4],
                  [4,5]]])
print(var2.ndim)
print(var2.shape)
print(var2.size)

print(var2[0])
print()
print(var2[0 ,1])
print()
print(var2[0,1,1])
print("sling 3d")
print(var2[0:1:1 , 0:1:1 , 0:1:1])
# print(var2[start:end:step , 0:1:1 , 0:1:1])

3
(2, 2, 2)
8
[[1 2]
 [1 2]]

[1 2]

2
sling 3d
[[[1]]]


In [247]:
# Iterating NumPy Arrays

In [253]:
# Iteration in 1D array
var1 = np.array([9,8,7,6,10])
print(len(var1))
for i in var1:
    print(i)

print("other way")
print(var1.size)
for i in range(len(var1)):
    print(var1[i])



5
9
8
7
6
10
other way
5
9
8
7
6
10


In [270]:
# Iteration in 2D array
var2 = np.array([[9,8,7],
                 [4,5,6]])
# print(len(var2))
# for i in range(len(var2)):
#     if i==0:
#         for j in range(len(var2[i])):
#             print(var2[i,j])
    
#     else:
#         for j in range(len(var2[i])):
#             print(var2[i,j])


for i in var2:
    for j in i:
        print(j)



9
8
7
4
5
6


In [275]:
# 3D array
var2 = np.array([[[1,2],
                  [1,2]],

                 [[3,4],
                  [4,5]]])

# by using range:
# for i in range(len(var2)):
#     for j in range(len(var2[i])):
#         for k in range(len(var2[i][j])):
#             print(var2[i,j,k])

# without using range direct

for i in var2:
    for j in i:
        for k in j:
            print(k)

print("done")

1
2
1
2
3
4
4
5
done


In [285]:
# we can also iterate by using function .. nditer()

var3 = np.array([[[1,2],
                  [1,2]],

                 [[3,4],
                  [4,5]]])
for i in np.nditer(var3):
    print(i)
# for i in np.nditer(var3 , flags=['buffered'], op_dtypes=["S"]):
#     print(i)
for i in np.nditer(var3 , flags=['buffered'], op_dtypes=["float"]):
    print(i)


1
2
1
2
3
4
4
5
1.0
2.0
1.0
2.0
3.0
4.0
4.0
5.0


In [288]:
#ndenumerate function
l=[3,4,9,2,7]
for i , j in enumerate(l):
    print(i,j)

arr = np.array([[[1,2],
                  [1,2]],

                 [[3,4],
                  [4,5]]])


print("Concept of ndenumerate")

for i,data in np.ndenumerate(arr):
    print(i,data)


0 3
1 4
2 9
3 2
4 7
Concept of ndenumerate
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 1
(0, 1, 1) 2
(1, 0, 0) 3
(1, 0, 1) 4
(1, 1, 0) 4
(1, 1, 1) 5


# Copy vs View in Numpy array

- Copy:
    - The Copy owns the data
    - the Copy of an array is a new Array
    - The Changes made in the copy data does not reflect in the original array

- View:
    - The view does not own the data.
    - A view of the original array.
    - Any changes made to the view will affect the original array, and any changes made to the original any will affect the view.    

In [295]:
x = np.array([2,4,5,6,7])
co = x.copy()
# do changes
x[1] = 0

print("original : ", x)
print("copied : ", co)

original :  [2 0 5 6 7]
copied :  [2 4 5 6 7]


In [297]:
x = np.array([2,4,5,6,7])
co = x.view()
# do changes
x[1] = 101

print("original : ", x)
print("copied : ", co)

original :  [  2 101   5   6   7]
copied :  [  2 101   5   6   7]


# Join and Split Functions NumPy Arrays

In [304]:
import numpy as np

var1 = np.array([1,2,4])
var2 = np.array([1,2,4,5])
ar = np.concatenate((var1,var2))
print(ar)


[1 2 4 1 2 4 5]


In [309]:
var1 = np.array([[1,2],
                 [3,5]])

var2 = np.array([[1,2],
                 [4,5]])
ar = np.concatenate((var1,var2), axis=1) # axis =0 means row wises, and axis =1 means column
ar1 = np.concatenate((var1,var2), axis=0) # axis =0 means row wises, and axis =1 means column
print(ar)
print()
print(ar1)

[[1 2 1 2]
 [3 5 4 5]]

[[1 2]
 [3 5]
 [1 2]
 [4 5]]


In [320]:
# stack Function
var1 = np.array([1,2,4,5])
var2 = np.array([1,2,4,5])

# a_new = np.stack((var1,var2), axis=1)
# a_new = np.hstack((var1,var2)) row
# a_new = np.vstack((var1,var2)) column
a_new = np.dstack((var1,var2)) # height
# a_new = np.stack((var1,var2), axis=0)
print(a_new)


[[[1 1]
  [2 2]
  [4 4]
  [5 5]]]


In [324]:
# Split Array : split the collection of array ..
var = np.array([1,2,4,5,6,7,8,8,9])
print(var)
ar = np.array_split(var , 5)
# ar = np.array_split(original arr , number of array) returns the list of arrays
print()

print(ar)
print()
for i in ar:
    print(i)

[1 2 4 5 6 7 8 8 9]

[array([1, 2]), array([4, 5]), array([6, 7]), array([8, 8]), array([9])]

[1 2]
[4 5]
[6 7]
[8 8]
[9]


In [327]:
var = np.array([[1,2],
                 [3,5]])

print(var)
# ar = np.array_split(var , 3)
ar = np.array_split(var , 3 , axis=1) # split along axis..
# ar = np.array_split(original arr , number of array) returns the list of arrays
print()

print(ar)
print()
for i in ar:
    print(i)

[[1 2]
 [3 5]]

[array([[1],
       [3]]), array([[2],
       [5]]), array([], shape=(2, 0), dtype=int32)]

[[1]
 [3]]
[[2]
 [5]]
[]


# Numpy Arrays Functions(search , sort , search Sorted , Filter)

In [340]:
# where keywords help to search
var = np.array([1,2,3,4,5,6,2,8,2,10])
x = np.where(var == 5) # where(write onley condition)
for i in x:
    print(i)

print(x)

[4]
(array([4], dtype=int64),)


In [344]:
# Search Sorted Array
var = np.array([1,2,3,4,5,6,2,8,2,10])
# x = np.searchsorted(var ,5)
# x = np.searchsorted(var ,5 , side = "right")
x = np.searchsorted(var ,[1,8,9], side = "right")
print(x)

[1 9 9]


In [345]:
# Sort array
var = np.array([1,3,4,5,6,2,8,10])
var = np.array([1,3,4,5,6,2,8,10])
print(np.sort(var))
# we can also sort the string by alphabet wise

[ 1  2  3  4  5  6  8 10]


In [351]:
var = np.array([[1,3,4],
                [5,6,2],
                [8,2,1]])
print(np.sort(var , axis=0)) # sort column wise
print(np.sort(var , axis=1)) # sort row wise


[[1 2 1]
 [5 3 2]
 [8 6 4]]
[[1 3 4]
 [2 5 6]
 [1 2 8]]


In [352]:
# Filter Array
var = np.array([1,3,4])
f = [False,False,True]

new_arr = var[f]
print(new_arr) # filtered array


[4]


### Function of Numpy
- Shuffle
- Unique
- Resize
- Flatten
- Ravel


In [353]:
#  np.random.shuffle
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 4 5 1 3]


In [357]:
# Unique

var = np.array([1,2,3,4,5,3,5,2,2,2,3])
# var1 = np.unique(var)
# var1 = np.unique(var , return_index=True)
var1 = np.unique(var , return_index=True , return_counts=True)
print(var1)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4], dtype=int64), array([1, 4, 3, 1, 2], dtype=int64))


In [364]:
# Resize Function
var = np.array([1,2,3,4,5,3,5,2,2,2,3])
x = np.resize(var , (2,3))
print(x)


[[1 2 3]
 [4 5 3]]


In [368]:
var = np.array([1,2,3,4,5,3,5,2,2,2,3])
# var = np.array([1,2,2,2])
x = var.reshape(1,-1)
print(x)

[[1 2 3 4 5 3 5 2 2 2 3]]


In [ ]:
#flatten convert 2,3,4 Dimension to one Dimension

In [373]:
var = np.array([[1,3,4],
                [5,6,2],
                [8,2,1]])

print(var.flatten())
print(var.flatten(order="F"))
print(var.ravel(order="A")) #F A K

[1 3 4 5 6 2 8 2 1]
[1 5 8 3 6 2 4 2 1]
[1 3 4 5 6 2 8 2 1]


### Numpy Insertion and Deletion

In [375]:
var = np.array([1,2,3,4,5,3,5,2,2,2,3])
x = np.insert(var , 2,40) # arr , position , value
print(x)


[ 1  2 40  3  4  5  3  5  2  2  2  3]


In [378]:
var = np.array([[1,3,4],
                [5,6,2],
                [8,2,1]])

# v1 = np.insert(var , 2 ,5,axis=0) # arr , index , data , axis
# v1 = np.insert(var , 2 ,[4,5,8],axis=0) # arr , index , data , axis
v1 = np.insert(var , 2 ,[4,5,8],axis=1) # arr , index , data , axis
print(v1)

[[1 3 4 4]
 [5 6 5 2]
 [8 2 8 1]]


In [380]:
# append function append at last along axis..
var = np.array([1,2,3,4,5,3,5,2,2,2,3])
x = np.append(var ,6) # arr , position , value
print(x)

[1 2 3 4 5 3 5 2 2 2 3 6]


In [382]:
var = np.array([[1,3,4],
                [5,6,2],
                [8,2,1]])
v1 = np.append(var , [[2,3,4]], axis =0)

In [383]:
print(v1)

[[1 3 4]
 [5 6 2]
 [8 2 1]
 [2 3 4]]


In [384]:
# Delete in arr
var = np.array([1,2,3])
x = np.delete(var ,1) # arr  index
print(x)


[1 3]


# Matrix in NumPy Arrays

In [387]:
# matrix addition
var1 = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))
print()
print(var1+var2)


[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]


In [391]:
# matrix multiplication
var1 = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
print(var1)
print(type(var1))
print()
print(var1*var2)
print()
print(var1.dot(var2))


[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


# Matrix Functions in NumPY Arrays
- Transpose
- Swapases
- Inverse
- Power
- Determinate

In [398]:
# Transpose
var = np.matrix([[1,2,3],[5,6,7]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)
print("0 axis changing into 1 axis")
print(np.swapaxes(var,0,1))


[[1 2 3]
 [5 6 7]]

[[1 5]
 [2 6]
 [3 7]]

[[1 5]
 [2 6]
 [3 7]]
0 axis changing into 1 axis
[[1 5]
 [2 6]
 [3 7]]


In [401]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [402]:
# Inverse Matrix - A^-1
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3))




[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [408]:
# Power of Matrix

var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.matrix_power(var4,2)) # power = 2
print(np.linalg.matrix_power(var4,1)) # power = 1
print(np.linalg.matrix_power(var4,0)) # power = 0
print(np.linalg.matrix_power(var4,-1)) # power = -1

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]
[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [411]:
#  Determinant of matrix...only square matix have determinant
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.det(var4))

[[1 2]
 [3 4]]

-2.0000000000000004
